### ISSUE TITLE
Need a config option to allow not merging certain `allOf` schemas

### ISSUE THREAD

**Issue by eliaslevy** [mokkabonna/json-schema-merge-allof#23]
`allOf` schemas using multiple conditional schemas using `if`, `then`, and `else` cannot be merged.  E.g.
```yaml
  allOf:
    - if:   { properties: { foo: { const: true } } }
      then: { required: [ bar ] }
    - if:   { properties: { xyz: { const: true } } }
      then: { required: [ abc ] } 
```

There is no way to write a resolver for `if` and `then`.

If would be useful to have an option that tell the library to skip trying to resolve certain schema keys and leave them in the `allOf`.
